<robot xmlns:xacro="http://ros.org/wiki/xacro" name="rov">

  <ros2_control name="ThrusterSystem" type="system">
    <hardware>
      <plugin>rov_control/ThrusterHardwareInterface</plugin>
    </hardware>
    <joint name="front_left_bottom_thruster_joint"/>
    <joint name="front_right_bottom_thruster_joint"/>
    <joint name="front_left_top_thruster_joint"/>
    <joint name="front_right_top_thruster_joint"/>
    <joint name="back_left_bottom_thruster_joint"/>
    <joint name="back_right_bottom_thruster_joint"/>
    <joint name="back_left_top_thruster_joint"/>
    <joint name="back_right_top_thruster_joint"/>
  </ros2_control>

  <!-- Constants -->
  <xacro:property name="pi" value="3.141592653589793"/>

  <!-- Thruster  Macro -->
<xacro:macro name="thruster" params="name x y z roll pitch yaw">
  <!-- Link and Joint -->
  <link name="${name}"/>
  <joint name="${name}_joint" type="fixed">
    <parent link="base_link"/>
    <child link="${name}"/>
    <origin 
      xyz="${x * 0.001} ${y * 0.001} ${z * 0.001}" 
      rpy="${
        roll * pi / 180.0
      } ${
        pitch * pi / 180.0
      } ${
        yaw * pi / 180.0
      }"
    />
  </joint>

  <!-- Transmission -->
  <transmission name="${name}_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${name}_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${name}_actuator">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>

  <!-- Thruster Properties -->
  <xacro:property name="pitch_offset" value="45"/>
  <xacro:property name="yaw_offset" value="45"/>
  <xacro:property name="x_offset" value="16"/>
  <xacro:property name="y_offset" value="30"/>
  <xacro:property name="z_offset" value="16"/>
  

  <!-- Thrusters -->
  <xacro:thruster name="front_left_bottom_thruster" x="${-x_offset}" y="${y_offset}" z="${-z_offset}" roll="0" pitch="${-pitch_offset}" yaw="${270 + yaw_offset}"/>
  <xacro:thruster name="front_right_bottom_thruster" x="${x_offset}" y="${y_offset}" z="${-z_offset}" roll="0" pitch="${-pitch_offset}" yaw="${yaw_offset}"/>
  <xacro:thruster name="front_left_top_thruster" x="${-x_offset}" y="${y_offset}" z="${z_offset}" roll="0" pitch="${pitch_offset}" yaw="${270 + yaw_offset}"/>
  <xacro:thruster name="front_right_top_thruster" x="${x_offset}" y="${y_offset}" z="${z_offset}" roll="0" pitch="${pitch_offset}" yaw="${yaw_offset}"/>
  <xacro:thruster name="back_left_bottom_thruster" x="${-x_offset}" y="${-y_offset}" z="${-z_offset}" roll="0" pitch="${-pitch_offset}" yaw="${180 + yaw_offset}"/>
  <xacro:thruster name="back_right_bottom_thruster" x="${x_offset}" y="${-y_offset}" z="${-z_offset}" roll="0" pitch="${-pitch_offset}" yaw="${90 + yaw_offset}"/>
  <xacro:thruster name="back_left_top_thruster" x="${-x_offset}" y="${-y_offset}" z="${z_offset}" roll="0" pitch="${pitch_offset}" yaw="${180 + yaw_offset}"/>
  <xacro:thruster name="back_right_top_thruster" x="${x_offset}" y="${-y_offset}" z="${z_offset}" roll="0" pitch="${pitch_offset}" yaw="${90 + yaw_offset}"/>

</robot>
