hardware:
  - name: ThrusterSystem
    type: system
    plugin: rov_control/ThrusterHardwareInterface
    parameters:
      pwm_freq_hz: 50
      pwm_min_µs: 1000
      pwm_max_µs: 2000
      pwm_mid_µs: 1500
    joints:
      - front_left_bottom_thruster_joint
      - front_right_bottom_thruster_joint
      - front_left_top_thruster_joint
      - front_right_top_thruster_joint
      - back_left_bottom_thruster_joint
      - back_right_bottom_thruster_joint
      - back_left_top_thruster_joint
      - back_right_top_thruster_joint
    command_interfaces:
      - name: effort
    state_interfaces:
      - name: velocity