controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    controller_chains:
      - top_controller: thruster_pid_controller
        chain:
          - thruster_pid_controller
          - axis_to_command_controller
    diagnostics:
      threshold:
        controller_manager:
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_devation:
              error: 10.0
              warn: 5.0

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    thruster_pid_controller:
      type: rov_controllers/PidController
      ros__parameters:
        dof_names: ["surge", "sway", "heave", "roll", "pitch", "yaw"]
        command_interface: effort
        reference_and_state_interfaces: [velocity]
        gains.surge: [5.0, 0.0, 2.0, 2.0, -2.0] # [p, i, d, i_clamp_max, i_clamp_min]
        gains.sway:  [5.0, 0.0, 2.0, 2.0, -2.0] # [p, i, d, i_clamp_max, i_clamp_min]
        gains.heave: [6.0, 0.0, 3.0, 2.0, -2.0] # [p, i, d, i_clamp_max, i_clamp_min]
        gains.roll:  [3.0, 0.0, 1.0, 1.0, -1.0] # [p, i, d, i_clamp_max, i_clamp_min]
        gains.pitch: [3.0, 0.0, 1.0, 1.0, -1.0] # [p, i, d, i_clamp_max, i_clamp_min]
        gains.yaw:   [3.0, 0.0, 1.5, 1.0, -1.0] # [p, i, d, i_clamp_max, i_clamp_min]

    axis_to_command_controller:
      type: rov_controllers/AxisToCommandController
      ros__parameters:
        joints: [
          "front_left_bottom_thruster_joint",
          "front_right_bottom_thruster_joint",
          "front_left_top_thruster_joint",
          "front_right_top_thruster_joint",
          "back_left_bottom_thruster_joint",
          "back_right_bottom_thruster_joint",
          "back_left_top_thruster_joint",
          "back_right_top_thruster_joint"
        ]
        position_offset: [16, 30, 16] # centimeters, [x, y, z]
        rotation_offset: [45, 45]     # degrees, [pitch, yaw]
        forward_max_thrust: 20.0      # Newtons
        reverse_max_thrust: 15.0      # Newtons
        wrench_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        effort_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        qp_time_limit: 50             # ms

        prim_res_threshold: 1e-2
        dual_res_threshold: 1e-2