gamepad_parser:
  ros__parameters:
    axes:
      left_stick_x:  {binding: "sway", index: 0}
      left_stick_y:  {binding: "surge", index: 1}
      right_stick_x: {binding: "yaw", index: 3}
      right_stick_y: {binding: "heave", index: 4}
      left_trigger:  {binding: "", index: 2}
      right_trigger: {binding: "", index: 5}
      dpad_x:        {binding: "roll", index: 6}
      dpad_y:        {binding: "pitch", index: 7}
    buttons:
      a:                  {binding: "", index: 0}
      b:                  {binding: "", index: 1}
      x:                  {binding: "", index: 2}
      y:                  {binding: "", index: 3}
      left_bumper:        {binding: "", index: 4}
      right_bumper:       {binding: "", index: 5}
      left_stick_button:  {binding: "", index: 9}
      right_stick_button: {binding: "", index: 10}
      menu_button:        {binding: "", index: 7}
      view_button:        {binding: "", index: 6}
      upload_button:      {binding: "", index: 11}
      xbox_button:        {binding: "", index: 8}